server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: loginModule
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**
        - id: paymentModule
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
        - id: travelerModule
          uri: lb://TRAVELER-SERVICE
          predicates:
            - Path=/traveler/**
        - id: travelerModule
          uri: lb://TICKET-CATALOGUE-SERVICE
          predicates:
            - Path=/ticketCatalogue/**

