package it.polito.wa2.login_service.unit_tests

import it.polito.wa2.login_service.unit_tests.unit_tests_utils.EmailBaseClass
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest


@SpringBootTest
class EmailServiceUnitTests() : EmailBaseClass() {

    @Test
    fun wrongEmailFormat(){
        val toMail = "wrongFormatEmail"
        val subject = "Test Subject"
        val mailBody = "Test Body : LOREM IPSUM"

        Assertions.assertEquals(mailService.sendEmail(toMail, subject, mailBody),false)
        /*Assertions.assertThrows(javax.mail.SendFailedException::class.java) {
            mailService.sendEmail(toMail, subject, mailBody)
        }*/
    }

    @Test
    fun emptySubject(){
        val toMail = email
        val subject = ""
        val mailBody = "Test Body : LOREM IPSUM"

        val email = sendAndReceiveEmail{
            mailService.sendEmail(toMail, subject, mailBody)
        }

        Assertions.assertEquals(toMail, email.from, "Wrong email address")
        Assertions.assertEquals(subject, email.subject.trim().replace("\r", ""), "Wrong subject")
        Assertions.assertEquals(mailBody, email.body.trim().replace("\r", ""), "Wrong body")
    }

    @Test
    fun emptyBody(){
        val toMail = email
        val subject = "Test Subject"
        val mailBody = ""

        val email = sendAndReceiveEmail{
            mailService.sendEmail(toMail, subject, mailBody)
        }

        //after many empty body requests, gmail sent back a mail delivery subsystem message of error
        Assertions.assertEquals("mailer-daemon@googlemail.com", email.from, "Wrong email address")
        Assertions.assertEquals("Delivery Status Notification (Failure)", email.subject.trim().replace("\r", ""), "Wrong subject")
        // mail body is autogenerated dynamically
        //Assertions.assertEquals("javax.mail.internet.MimeMultipart@21139739", email.body.trim().replace("\r", ""), "Wrong body")
    }

    @Test
    fun correctEmail(){
        val toMail = email
        val subject = "Test Subject"
        val mailBody = "Test Body : LOREM IPSUM"

        val email = sendAndReceiveEmail{
            mailService.sendEmail(toMail, subject, mailBody)
        }

        Assertions.assertEquals(toMail, email.from, "Wrong email address")
        Assertions.assertEquals(subject, email.subject.trim().replace("\r", ""), "Wrong subject")
        Assertions.assertEquals(mailBody, email.body.trim().replace("\r", ""), "Wrong body")
    }



}